- name: install python3 packages
  ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
      loop:
       - python3 
       - gcc 
       - python3-devel
- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup.yaml
- name: install dependencies
  ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
  args:
      chdir: /app
- name: start the payment service
  include_role:
    name: common
    tasks_from: systemd.yaml