   - name: install mysql
     ansible.builtin.package:
        name: mysql-server
        state: present
   - name: enable and start mysql
     ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started 
   - name: set user name and password
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1  