- name: "copy the {{ component }} service to systemd" 
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: "enable and restart {{ component }} service"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted 
    enabled: yes