- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup.yaml
- name: setup-nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml
- name: start the cart service
  include_role:
    name: common
    tasks_from: systemd.yaml
    
